arm_1_joint_controller:
  type: "position_controllers/JointPositionController"
  joint: "arm1_joint"
  pid: {p: 10.0, i: 0.05, d: 1.0}

arm_2_joint_controller:
  type: "position_controllers/JointPositionController"
  joint: "arm2_joint"
  pid: {p: 10.0, i: 0.05, d: 1.0}

joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50